specVersion: 0.0.1
description: Data analysis - Kusama
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded

        - handler: handleUnbonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded

        - handler: handleRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
 
        - handler: handleSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed

        - handler: handleWithdraw
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Withdrawn